In [1]:
from pathlib import Path
import pandas as pd
import sys

# путь до корня проекта
PROJECT_ROOT = Path("../../").resolve()

# добавляем в PYTHONPATH
sys.path.append(str(PROJECT_ROOT))

from src.utils.preprocess import (
    preprocess_initial_dataset,
    remove_log_features,
    split_dataset_with_val,
    train_catboost_model,
    get_feature_importance_df,
    transform_contact_region_pvz
)




pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

DATA_PATH = Path("../../data/cleaned_dataset/final_dataset_from_notebooks.csv")
RAW_DATA_PATH = Path("../../data/raw/clean_dataset.csv")
XSLX_PATH = Path("../../data/raw/PvzList_rus-2.xlsx")

In [2]:
df = pd.read_csv(DATA_PATH)
df_raw = pd.read_csv(RAW_DATA_PATH)
df = df.merge(
    df_raw[
        ["row_id", "lead_Стоимость доставки", "lead_Масса (гр)", "lead_Высота", "contact_Код ПВЗ"]
    ],
    on="row_id",
    how="left",
)
df = df.drop(columns="contact_region_pvz")
pvz_data = pd.read_excel(XSLX_PATH, sheet_name="Россия", usecols=[0, 1, 2], engine='openpyxl')
df = transform_contact_region_pvz(df, pvz_data)
df = remove_log_features(df)
del df_raw
# Приводим всё к нужному типу
df = preprocess_initial_dataset(df)
df = df.drop(columns="contact_Код ПВЗ")
df.info()

C:\Users\Михаил\AppData\Local\Temp\ipykernel_9156\1309604265.py:2: DtypeWarning: Columns (79,80,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv(RAW_DATA_PATH)

<class 'pandas.core.frame.DataFrame'>
Index: 17966 entries, 0 to 18787
Columns: 110 entries, contact_pvz_code to contact_has_pvz_code
dtypes: datetime64[ns](2), float64(18), int64(64), object(26)
memory usage: 15.2+ MB

In [27]:
print(*df.columns.tolist(), sep="\n")

contact_pvz_code
lead_weight_gm
lead_responsible_user_id
lead_utm_group
lead_utm_referrer
lead_tags
lead_utm_source
lead_Квалификация лида
is_responsible_same
has_weight
lead_utm_referrer_site
lead_has_roistat
lead_utm_id_1
lead_utm_id_2
lead_utm_id_3
lead_utm_device_type
lead_utm_site
lead_utm_position
lead_utm_reatrgeting_id
lead_utm_region_name
lead_is_utm_campaign_type_1
contact_Город
contact_region
lead_manager_category
lead_rate_is_warehouse_to_warehouse
lead_formname_has_value
lead_has_creation_date
lead_creation_date_week
lead_creation_date_month
lead_creation_date_quarter
lead_creation_date_dayofweek
lead_creation_date_sin
lead_creation_date_cos
sale_date_month
sale_date_quarter
sale_date_dayofweek
sale_date_week
sale_date_sin
sale_date_cos
lead_items_count
lead_total_quantity
lead_total_cost_from_composition
lead_has_health_supplement
lead_has_pillow
lead_has_mattress
lead_has_brace
lead_has_footwear
lead_has_accessory
lead_has_health_product
lead_categories_count
lead_has_linear_width
lead_linear_width
lead_discount_category
lead_discount
sale_hour
sale_dayofweek
sale_month
sale_ts
lead_source
timedelta_between_sale_and_creation
lead_created_ts
lead_created_dayofweek
lead_created_hour
lead_created_month
lead_has_shipping_cost
lead_shipping_cost
lead_has_length
lead_length
lead_price
lead_group_id
buyout_flag
width_cat
width_is_missing
lead_payment_type
lead_delivery_type
lead_group_id_missing
lead_group_quality
lead_mass_known
contact_to_lead_hours
contact_missing
contact_hour
contact_dayofweek
contact_month
contact_is_weekend
is_paid_traffic
lead_category_freq
is_feature_phone
lead_utm_campaign_missing
lead_utm_campaign_grouped
traffic_source_missing
traffic_source_grouped
utm_term_missing
utm_term_grouped
utm_sky_missing
utm_sky_autotarget
utm_sky_brand
utm_sky_varicose
utm_sky_sleep
lead_group_missing
lead_group_grouped
problem_missing
problem_grouped
lead_height_known
lead_height_bin
delivery_cost_missing
lead_Стоимость доставки
lead_Масса (гр)
lead_Высота
contact_region_pvz
contact_has_pvz_code

Удаляем из модели субъективную оценку менеджеров

Удаляем lead_group_quality так как потенциально содержит данные из будущего

In [ ]:
df_reduced = df.drop(columns=["lead_Квалификация лида", "lead_group_quality"])

X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_reduced)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления lead_group_quality:", metrics)

In [29]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.head(20)

                                 feature  importance
70                     lead_payment_type   15.961591
5                              lead_tags    4.395064
3                         lead_utm_group    3.847163
14                  lead_utm_device_type    3.729870
99                       lead_height_bin    3.425300
91                         utm_sky_brand    2.971248
71                    lead_delivery_type    2.957815
6                        lead_utm_source    2.833583
38                      lead_items_count    2.256896
57   timedelta_between_sale_and_creation    2.149461
65                           lead_length    2.041855
103                          lead_Высота    1.957536
74                 contact_to_lead_hours    1.860046
16                     lead_utm_position    1.856628
35                        sale_date_week    1.852018
77                     contact_dayofweek    1.834751
67                         lead_group_id    1.812785
36                         sale_date_sin    1.736080
12                         lead_utm_id_2    1.659583
68                             width_cat    1.656530

✅ Улучшение! Удаление признака lead_price дало PR_AUC = 0.378325

In [ ]:
df_reduced = df_reduced.drop(columns=["lead_price"])

X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_reduced)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления lead_price:", metrics)

In [31]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.head(20)

                              feature  importance
69                  lead_payment_type   24.923440
3                      lead_utm_group    7.278075
5                           lead_tags    6.592564
40   lead_total_cost_from_composition    5.092226
14               lead_utm_device_type    4.743109
56                        lead_source    4.514615
90                      utm_sky_brand    3.148211
66                      lead_group_id    2.714166
58                    lead_created_ts    2.481648
35                     sale_date_week    2.450030
70                 lead_delivery_type    2.370152
34                sale_date_dayofweek    2.245220
4                   lead_utm_referrer    2.193672
8                          has_weight    2.045869
94                 lead_group_grouped    1.831191
103                contact_region_pvz    1.788757
102                       lead_Высота    1.700215
86                   utm_term_missing    1.685558
65                        lead_length    1.640110
9              lead_utm_referrer_site    1.361999

✅ Улучшение! Удаление признака width_is_missing дало PR_AUC = 0.389970

In [5]:
df_reduced = df_reduced.drop(columns=["width_is_missing"])

X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_reduced)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления width_is_missing:", metrics)

0:	learn: 0.6375452	test: 0.6146247	best: 0.6146247 (0)	total: 212ms	remaining: 7m 3s
100:	learn: 0.7723262	test: 0.6676735	best: 0.6743555 (12)	total: 6.98s	remaining: 2m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6743554887
bestIteration = 12

Shrink model to first 13 iterations.
Метрики после удаления width_is_missing: {'ROC_AUC': 0.6711080314827352, 'PR_AUC': 0.3899703955089175, 'LogLoss': 0.6843715345224443}

In [6]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.head(20)

                        feature  importance
68            lead_payment_type   22.579310
14         lead_utm_device_type   10.070237
13                lead_utm_id_3    9.492683
5                     lead_tags    6.522557
3                lead_utm_group    4.893978
65                  lead_length    4.857552
69           lead_delivery_type    3.995333
9        lead_utm_referrer_site    3.816106
58              lead_created_ts    3.029497
11                lead_utm_id_1    2.844528
28   lead_creation_date_quarter    2.732843
92           lead_group_missing    2.419905
97              lead_height_bin    1.939635
8                    has_weight    1.882452
81    lead_utm_campaign_missing    1.782317
98        delivery_cost_missing    1.628525
4             lead_utm_referrer    1.570568
67                    width_cat    1.506039
54               sale_dayofweek    1.500936
101                 lead_Высота    1.182793

In [35]:
baseline_pr_auc = 0.3899703955089175

results = []

for feature in fi["feature"]:
    print(f"\nУдаляем признак: {feature}")

    df_removed = df_reduced.drop(columns=[feature])

    X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
        df_removed
    )

    model, metrics = train_catboost_model(
        X_train, y_train, X_val, y_val, X_test, y_test
    )

    pr_auc = metrics["PR_AUC"]

    print(f"PR_AUC: {pr_auc:.6f}")

    results.append((feature, pr_auc))

    # проверка улучшения
    if pr_auc > baseline_pr_auc:
        print(f"✅ Улучшение! Удаление признака {feature} дало PR_AUC = {pr_auc:.6f}")

Удаляем признак: lead_payment_type
0:	learn: 0.6176356	test: 0.6222230	best: 0.6222230 (0)	total: 64ms	remaining: 2m 7s
100:	learn: 0.7738426	test: 0.6521000	best: 0.6723571 (39)	total: 6.79s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6723570928
bestIteration = 39

Shrink model to first 40 iterations.
PR_AUC: 0.338283

Удаляем признак: lead_utm_device_type
0:	learn: 0.6514430	test: 0.6722305	best: 0.6722305 (0)	total: 62.4ms	remaining: 2m 4s
100:	learn: 0.7745041	test: 0.6865123	best: 0.6875451 (99)	total: 6.59s	remaining: 2m 3s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6875450818
bestIteration = 99

Shrink model to first 100 iterations.
PR_AUC: 0.362323

Удаляем признак: lead_utm_id_3
0:	learn: 0.6516250	test: 0.6422620	best: 0.6422620 (0)	total: 61.5ms	remaining: 2m 3s
100:	learn: 0.7708934	test: 0.6686728	best: 0.6825078 (8)	total: 6.96s	remaining: 2m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6825078067
bestIteration = 8

Shrink model to first 9 iterations.
PR_AUC: 0.331942

Удаляем признак: lead_tags
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 60.5ms	remaining: 2m
100:	learn: 0.7746780	test: 0.6653750	best: 0.6737020 (11)	total: 6.8s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6737020103
bestIteration = 11

Shrink model to first 12 iterations.
PR_AUC: 0.376349

Удаляем признак: lead_utm_group
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 63.5ms	remaining: 2m 6s
100:	learn: 0.7761833	test: 0.6592067	best: 0.6764684 (20)	total: 6.71s	remaining: 2m 6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6764684423
bestIteration = 20

Shrink model to first 21 iterations.
PR_AUC: 0.370876

Удаляем признак: lead_length
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 63.4ms	remaining: 2m 6s
100:	learn: 0.7727766	test: 0.6693427	best: 0.6742113 (72)	total: 6.86s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6742113402
bestIteration = 72

Shrink model to first 73 iterations.
PR_AUC: 0.289527

Удаляем признак: lead_delivery_type
0:	learn: 0.6663689	test: 0.6425419	best: 0.6425419 (0)	total: 62ms	remaining: 2m 4s
100:	learn: 0.7704880	test: 0.6619505	best: 0.6698403 (37)	total: 6.62s	remaining: 2m 4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6698402985
bestIteration = 37

Shrink model to first 38 iterations.
PR_AUC: 0.272913

Удаляем признак: lead_utm_referrer_site
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 62.2ms	remaining: 2m 4s
100:	learn: 0.7802044	test: 0.6650129	best: 0.6685931 (35)	total: 6.78s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6685930624
bestIteration = 35

Shrink model to first 36 iterations.
PR_AUC: 0.249617

Удаляем признак: lead_created_ts
0:	learn: 0.6486197	test: 0.6359212	best: 0.6359212 (0)	total: 62.6ms	remaining: 2m 5s
100:	learn: 0.7765419	test: 0.6677102	best: 0.6737433 (60)	total: 6.83s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6737433384
bestIteration = 60

Shrink model to first 61 iterations.
PR_AUC: 0.332681

Удаляем признак: lead_utm_id_1
0:	learn: 0.6520829	test: 0.6433058	best: 0.6433058 (0)	total: 62ms	remaining: 2m 3s
100:	learn: 0.7747041	test: 0.6648947	best: 0.6688884 (55)	total: 6.83s	remaining: 2m 8s
200:	learn: 0.8686091	test: 0.6698064	best: 0.6748694 (139)	total: 13.8s	remaining: 2m 3s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6748694337
bestIteration = 139

Shrink model to first 140 iterations.
PR_AUC: 0.278090

Удаляем признак: lead_creation_date_quarter
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 63.2ms	remaining: 2m 6s
100:	learn: 0.7742609	test: 0.6673597	best: 0.6771984 (77)	total: 6.87s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6771984091
bestIteration = 77

Shrink model to first 78 iterations.
PR_AUC: 0.270058

Удаляем признак: lead_group_missing
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 61.6ms	remaining: 2m 3s
100:	learn: 0.7764688	test: 0.6511124	best: 0.6836808 (4)	total: 7.06s	remaining: 2m 12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6836808207
bestIteration = 4

Shrink model to first 5 iterations.
PR_AUC: 0.324002

Удаляем признак: lead_height_bin
0:	learn: 0.6663689	test: 0.6425419	best: 0.6425419 (0)	total: 61.4ms	remaining: 2m 2s
100:	learn: 0.7812999	test: 0.6620740	best: 0.6734934 (37)	total: 6.75s	remaining: 2m 6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6734933548
bestIteration = 37

Shrink model to first 38 iterations.
PR_AUC: 0.267373

Удаляем признак: has_weight
0:	learn: 0.6422948	test: 0.6659467	best: 0.6659467 (0)	total: 61ms	remaining: 2m 2s
100:	learn: 0.7778111	test: 0.6718200	best: 0.6923252 (8)	total: 6.91s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6923251654
bestIteration = 8

Shrink model to first 9 iterations.
PR_AUC: 0.354659

Удаляем признак: lead_utm_campaign_missing
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 61.9ms	remaining: 2m 3s
100:	learn: 0.7674639	test: 0.6677323	best: 0.6853344 (4)	total: 6.79s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6853343511
bestIteration = 4

Shrink model to first 5 iterations.
PR_AUC: 0.324364

Удаляем признак: delivery_cost_missing
0:	learn: 0.6294715	test: 0.6817806	best: 0.6817806 (0)	total: 61.6ms	remaining: 2m 3s
100:	learn: 0.7790178	test: 0.6680541	best: 0.6817806 (0)	total: 6.9s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6817806427
bestIteration = 0

Shrink model to first 1 iterations.
PR_AUC: 0.302250

Удаляем признак: lead_utm_referrer
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 61.4ms	remaining: 2m 2s
100:	learn: 0.7697363	test: 0.6676221	best: 0.6739998 (22)	total: 6.62s	remaining: 2m 4s
200:	learn: 0.8695485	test: 0.6748549	best: 0.6768260 (191)	total: 13.5s	remaining: 2m 1s
300:	learn: 0.9154012	test: 0.6731361	best: 0.6814891 (235)	total: 20.5s	remaining: 1m 55s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6814891229
bestIteration = 235

Shrink model to first 236 iterations.
PR_AUC: 0.318708

Удаляем признак: width_cat
0:	learn: 0.6514430	test: 0.6722305	best: 0.6722305 (0)	total: 64.3ms	remaining: 2m 8s
100:	learn: 0.7704793	test: 0.6516257	best: 0.6803684 (21)	total: 6.62s	remaining: 2m 4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6803683922
bestIteration = 21

Shrink model to first 22 iterations.
PR_AUC: 0.348034

Удаляем признак: sale_dayofweek
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 61.4ms	remaining: 2m 2s
100:	learn: 0.7710920	test: 0.6492591	best: 0.6622929 (6)	total: 6.82s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6622929419
bestIteration = 6

Shrink model to first 7 iterations.
PR_AUC: 0.254343

Удаляем признак: lead_Высота
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 60.7ms	remaining: 2m 1s
100:	learn: 0.7741401	test: 0.6852434	best: 0.6856155 (98)	total: 7s	remaining: 2m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6856155221
bestIteration = 98

Shrink model to first 99 iterations.
PR_AUC: 0.327475

Удаляем признак: sale_date_week
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 61.2ms	remaining: 2m 2s
100:	learn: 0.7798705	test: 0.6647516	best: 0.6724506 (41)	total: 7.21s	remaining: 2m 15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6724506251
bestIteration = 41

Shrink model to first 42 iterations.
PR_AUC: 0.368549

Удаляем признак: lead_discount_category
0:	learn: 0.6514430	test: 0.6722305	best: 0.6722305 (0)	total: 61.3ms	remaining: 2m 2s
100:	learn: 0.7786231	test: 0.6802596	best: 0.6802596 (100)	total: 6.78s	remaining: 2m 7s
200:	learn: 0.8688295	test: 0.6466735	best: 0.6802596 (100)	total: 13.7s	remaining: 2m 2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.680259643
bestIteration = 100

Shrink model to first 101 iterations.
PR_AUC: 0.296579

Удаляем признак: lead_creation_date_week
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 61.9ms	remaining: 2m 3s
100:	learn: 0.7726562	test: 0.6777574	best: 0.6806904 (65)	total: 6.77s	remaining: 2m 7s
200:	learn: 0.8630109	test: 0.6788121	best: 0.6846170 (154)	total: 13.7s	remaining: 2m 2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6846170344
bestIteration = 154

Shrink model to first 155 iterations.
PR_AUC: 0.260055

Удаляем признак: lead_utm_reatrgeting_id
0:	learn: 0.6516250	test: 0.6422620	best: 0.6422620 (0)	total: 60.6ms	remaining: 2m 1s
100:	learn: 0.7783006	test: 0.6578720	best: 0.6713020 (6)	total: 6.9s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6713019711
bestIteration = 6

Shrink model to first 7 iterations.
PR_AUC: 0.298535

Удаляем признак: sale_date_month
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 61.9ms	remaining: 2m 3s
100:	learn: 0.7776869	test: 0.6698903	best: 0.6865574 (11)	total: 6.79s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6865574046
bestIteration = 11

Shrink model to first 12 iterations.
PR_AUC: 0.363208

Удаляем признак: contact_has_pvz_code
0:	learn: 0.6294715	test: 0.6817806	best: 0.6817806 (0)	total: 61.8ms	remaining: 2m 3s
100:	learn: 0.7701495	test: 0.6747771	best: 0.6922396 (1)	total: 6.76s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6922395978
bestIteration = 1

Shrink model to first 2 iterations.
PR_AUC: 0.372888

Удаляем признак: contact_to_lead_hours
0:	learn: 0.6359740	test: 0.6066199	best: 0.6066199 (0)	total: 71.6ms	remaining: 2m 23s
100:	learn: 0.7740622	test: 0.6808022	best: 0.6817384 (96)	total: 7.11s	remaining: 2m 13s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6817384304
bestIteration = 96

Shrink model to first 97 iterations.
PR_AUC: 0.326908

Удаляем признак: lead_linear_width
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 60.2ms	remaining: 2m
100:	learn: 0.7813225	test: 0.6533682	best: 0.6717828 (29)	total: 6.93s	remaining: 2m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6717828479
bestIteration = 29

Shrink model to first 30 iterations.
PR_AUC: 0.345943

Удаляем признак: lead_group_id
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 61.3ms	remaining: 2m 2s
100:	learn: 0.7730867	test: 0.6651848	best: 0.6741983 (7)	total: 6.83s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.674198291
bestIteration = 7

Shrink model to first 8 iterations.
PR_AUC: 0.343038

Удаляем признак: lead_utm_position
0:	learn: 0.6516250	test: 0.6422620	best: 0.6422620 (0)	total: 62.4ms	remaining: 2m 4s
100:	learn: 0.7803114	test: 0.6648555	best: 0.6829372 (8)	total: 6.83s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.682937183
bestIteration = 8

Shrink model to first 9 iterations.
PR_AUC: 0.334234

Удаляем признак: lead_Стоимость доставки
0:	learn: 0.6482917	test: 0.6615912	best: 0.6615912 (0)	total: 64.2ms	remaining: 2m 8s
100:	learn: 0.7802018	test: 0.6725128	best: 0.6777179 (6)	total: 6.99s	remaining: 2m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.677717878
bestIteration = 6

Shrink model to first 7 iterations.
PR_AUC: 0.342823

Удаляем признак: lead_creation_date_dayofweek
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 61.8ms	remaining: 2m 3s
100:	learn: 0.7762741	test: 0.6708408	best: 0.6718717 (98)	total: 6.85s	remaining: 2m 8s
200:	learn: 0.8626982	test: 0.6698738	best: 0.6738666 (110)	total: 13.8s	remaining: 2m 3s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6738666323
bestIteration = 110

Shrink model to first 111 iterations.
PR_AUC: 0.294446

Удаляем признак: contact_pvz_code
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 61.3ms	remaining: 2m 2s
100:	learn: 0.7801092	test: 0.6799215	best: 0.6896924 (80)	total: 6.7s	remaining: 2m 5s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6896923998
bestIteration = 80

Shrink model to first 81 iterations.
PR_AUC: 0.338841

Удаляем признак: contact_region_pvz
0:	learn: 0.6663689	test: 0.6425419	best: 0.6425419 (0)	total: 62.3ms	remaining: 2m 4s
100:	learn: 0.7773670	test: 0.6598911	best: 0.6763461 (51)	total: 6.83s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6763460716
bestIteration = 51

Shrink model to first 52 iterations.
PR_AUC: 0.300640

Удаляем признак: is_responsible_same
0:	learn: 0.6422948	test: 0.6659467	best: 0.6659467 (0)	total: 60.7ms	remaining: 2m 1s
100:	learn: 0.7689929	test: 0.6756485	best: 0.6895375 (6)	total: 6.99s	remaining: 2m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6895374969
bestIteration = 6

Shrink model to first 7 iterations.
PR_AUC: 0.356496

Удаляем признак: lead_utm_source
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 61.3ms	remaining: 2m 2s
100:	learn: 0.7764603	test: 0.6725683	best: 0.6756968 (53)	total: 6.64s	remaining: 2m 4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6756967514
bestIteration = 53

Shrink model to first 54 iterations.
PR_AUC: 0.348577

Удаляем признак: lead_utm_site
0:	learn: 0.6514430	test: 0.6722305	best: 0.6722305 (0)	total: 58.9ms	remaining: 1m 57s
100:	learn: 0.7709001	test: 0.6907285	best: 0.6907285 (100)	total: 6.73s	remaining: 2m 6s
200:	learn: 0.8683174	test: 0.6743125	best: 0.6907285 (100)	total: 13.6s	remaining: 2m 1s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.690728453
bestIteration = 100

Shrink model to first 101 iterations.
PR_AUC: 0.355122

Удаляем признак: lead_utm_id_2
0:	learn: 0.6516250	test: 0.6422620	best: 0.6422620 (0)	total: 61.6ms	remaining: 2m 3s
100:	learn: 0.7836548	test: 0.6554916	best: 0.6825078 (8)	total: 7.14s	remaining: 2m 14s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6825078067
bestIteration = 8

Shrink model to first 9 iterations.
PR_AUC: 0.331942

Удаляем признак: lead_weight_gm
0:	learn: 0.6430871	test: 0.6294682	best: 0.6294682 (0)	total: 61.2ms	remaining: 2m 2s
100:	learn: 0.7675289	test: 0.6599969	best: 0.6658993 (93)	total: 6.72s	remaining: 2m 6s
200:	learn: 0.8635981	test: 0.6597309	best: 0.6691962 (113)	total: 13.7s	remaining: 2m 3s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6691961816
bestIteration = 113

Shrink model to first 114 iterations.
PR_AUC: 0.279529

Удаляем признак: lead_responsible_user_id
0:	learn: 0.6516667	test: 0.6192676	best: 0.6192676 (0)	total: 59.2ms	remaining: 1m 58s
100:	learn: 0.7738150	test: 0.6651523	best: 0.6766257 (27)	total: 6.69s	remaining: 2m 5s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.676625731
bestIteration = 27

Shrink model to first 28 iterations.
PR_AUC: 0.250661

Удаляем признак: lead_total_quantity
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 61ms	remaining: 2m 1s
100:	learn: 0.7746360	test: 0.6585056	best: 0.6744129 (77)	total: 6.87s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6744128701
bestIteration = 77

Shrink model to first 78 iterations.
PR_AUC: 0.283166

Удаляем признак: lead_items_count
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 61.9ms	remaining: 2m 3s
100:	learn: 0.7714372	test: 0.6741136	best: 0.6743174 (99)	total: 6.68s	remaining: 2m 5s
200:	learn: 0.8645794	test: 0.6665256	best: 0.6750214 (105)	total: 13.7s	remaining: 2m 2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6750214283
bestIteration = 105

Shrink model to first 106 iterations.
PR_AUC: 0.284132

Удаляем признак: sale_date_cos
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 62.1ms	remaining: 2m 4s
100:	learn: 0.7738318	test: 0.6538037	best: 0.6622929 (6)	total: 6.88s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6622929419
bestIteration = 6

Shrink model to first 7 iterations.
PR_AUC: 0.254343

Удаляем признак: sale_date_sin
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 62.4ms	remaining: 2m 4s
100:	learn: 0.7734456	test: 0.6759714	best: 0.6810709 (68)	total: 6.79s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6810708532
bestIteration = 68

Shrink model to first 69 iterations.
PR_AUC: 0.302978

Удаляем признак: sale_date_dayofweek
0:	learn: 0.6472636	test: 0.6145860	best: 0.6145860 (0)	total: 61.1ms	remaining: 2m 2s
100:	learn: 0.7785203	test: 0.6612380	best: 0.6724506 (41)	total: 6.92s	remaining: 2m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6724506251
bestIteration = 41

Shrink model to first 42 iterations.
PR_AUC: 0.368549

Удаляем признак: sale_date_quarter
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 63.1ms	remaining: 2m 6s
100:	learn: 0.7776347	test: 0.6648383	best: 0.6865574 (11)	total: 6.8s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6865574046
bestIteration = 11

Shrink model to first 12 iterations.
PR_AUC: 0.363208

Удаляем признак: lead_creation_date_sin
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 64.2ms	remaining: 2m 8s
100:	learn: 0.7827046	test: 0.6494581	best: 0.6624728 (17)	total: 6.95s	remaining: 2m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6624728208
bestIteration = 17

Shrink model to first 18 iterations.
PR_AUC: 0.316850

Удаляем признак: lead_creation_date_cos
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 61.1ms	remaining: 2m 2s
100:	learn: 0.7810585	test: 0.6486922	best: 0.6624728 (17)	total: 6.81s	remaining: 2m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6624728208
bestIteration = 17

Shrink model to first 18 iterations.
PR_AUC: 0.316850

Удаляем признак: lead_formname_has_value
0:	learn: 0.6422948	test: 0.6659467	best: 0.6659467 (0)	total: 62ms	remaining: 2m 3s
100:	learn: 0.7726233	test: 0.6773534	best: 0.6895769 (7)	total: 6.79s	remaining: 2m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6895768695
bestIteration = 7

Shrink model to first 8 iterations.
PR_AUC: 0.360389

Удаляем признак: lead_creation_date_month
0:	learn: 0.6413742	test: 0.6210757	best: 0.6210757 (0)	total: 63ms	remaining: 2m 5s
100:	learn: 0.7786419	test: 0.6688693	best: 0.6736705 (33)	total: 7.1s	remaining: 2m 13s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6736705137
bestIteration = 33

Shrink model to first 34 iterations.
PR_AUC: 0.259895

Удаляем признак: lead_has_creation_date
0:	learn: 0.6422948	test: 0.6659467	best: 0.6659467 (0)	total: 63.2ms	remaining: 2m 6s
100:	learn: 0.7721730	test: 0.6675005	best: 0.6895769 (7)	total: 6.9s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6895768695
bestIteration = 7

Shrink model to first 8 iterations.
PR_AUC: 0.360389

Удаляем признак: lead_is_utm_campaign_type_1
0:	learn: 0.6422948	test: 0.6659467	best: 0.6659467 (0)	total: 60.3ms	remaining: 2m
100:	learn: 0.7753316	test: 0.6808760	best: 0.6895769 (7)	total: 6.87s	remaining: 2m 9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6895768695
bestIteration = 7

Shrink model to first 8 iterations.
PR_AUC: 0.360389

Удаляем признак: contact_Город
0:	learn: 0.6514430	test: 0.6722305	best: 0.6722305 (0)	total: 61.1ms	remaining: 2m 2s

In [36]:
results_df = pd.DataFrame(results, columns=["feature", "pr_auc"])
results_df = results_df.sort_values(by="pr_auc", ascending=False)

print(results_df[results_df["pr_auc"] > baseline_pr_auc])

Empty DataFrame
Columns: [feature, pr_auc]
Index: []

In [37]:
baseline_pr_auc = 0.3899703955089175

for n in range(90, 29, -1):
    col_to_drop = fi["feature"].tail(n).to_list()

    df_test = df_reduced.drop(columns=col_to_drop)

    X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_test)

    model, metrics = train_catboost_model(
        X_train, y_train, X_val, y_val, X_test, y_test
    )

    pr_auc = metrics["PR_AUC"]

    print(f"tail({n}) -> PR_AUC: {pr_auc:.6f}")

    if pr_auc > baseline_pr_auc:
        print("\nIMPROVEMENT FOUND")
        print(f"tail({n}) gives PR_AUC = {pr_auc:.6f} (baseline = {baseline_pr_auc})")
        break

0:	learn: 0.6409768	test: 0.6493899	best: 0.6493899 (0)	total: 49ms	remaining: 1m 37s
100:	learn: 0.7224334	test: 0.6692222	best: 0.6816220 (4)	total: 4.6s	remaining: 1m 26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6816219588
bestIteration = 4

Shrink model to first 5 iterations.
tail(90) -> PR_AUC: 0.355564
0:	learn: 0.6550814	test: 0.6530321	best: 0.6530321 (0)	total: 45.2ms	remaining: 1m 30s
100:	learn: 0.7202827	test: 0.6727969	best: 0.6744498 (93)	total: 4.71s	remaining: 1m 28s
200:	learn: 0.7660357	test: 0.6529815	best: 0.6756504 (108)	total: 9.65s	remaining: 1m 26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.675650373
bestIteration = 108

Shrink model to first 109 iterations.
tail(89) -> PR_AUC: 0.353945
0:	learn: 0.6465424	test: 0.6644386	best: 0.6644386 (0)	total: 43.9ms	remaining: 1m 27s
100:	learn: 0.7237571	test: 0.6835573	best: 0.6877731 (1)	total: 4.57s	remaining: 1m 25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6877731384
bestIteration = 1

Shrink model to first 2 iterations.
tail(88) -> PR_AUC: 0.371413
0:	learn: 0.6250918	test: 0.6609869	best: 0.6609869 (0)	total: 45.3ms	remaining: 1m 30s
100:	learn: 0.7319893	test: 0.7006587	best: 0.7015039 (99)	total: 4.8s	remaining: 1m 30s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7015038802
bestIteration = 99

Shrink model to first 100 iterations.
tail(87) -> PR_AUC: 0.406579

IMPROVEMENT FOUND
tail(87) gives PR_AUC = 0.406579 (baseline = 0.3899703955089175)

IMPROVEMENT FOUND\
tail(87) gives PR_AUC = 0.406579 (baseline = 0.3899703955089175)

In [ ]:
col_to_drop = fi["feature"].tail(87).to_list()

df_reduced = df_reduced.drop(columns=col_to_drop)
X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
    df_reduced
)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления 87 неважных признаков:", metrics)

0:	learn: 0.6250918	test: 0.6609869	best: 0.6609869 (0)	total: 48ms	remaining: 1m 35s
100:	learn: 0.7319893	test: 0.7006587	best: 0.7015039 (99)	total: 4.81s	remaining: 1m 30s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7015038802
bestIteration = 99

Shrink model to first 100 iterations.
Метрики после удаления 87 неважных признаков: {'ROC_AUC': 0.6761906525050778, 'PR_AUC': 0.40657857277830695, 'LogLoss': 0.6960768336903173}

In [39]:
X_train.columns.to_list()

['lead_utm_group',
 'lead_utm_referrer',
 'lead_tags',
 'has_weight',
 'lead_utm_referrer_site',
 'lead_utm_id_1',
 'lead_utm_id_3',
 'lead_utm_device_type',
 'lead_creation_date_quarter',
 'lead_created_ts',
 'lead_length',
 'lead_payment_type',
 'lead_delivery_type',
 'lead_utm_campaign_missing',
 'lead_group_missing',
 'lead_height_bin',
 'delivery_cost_missing']

In [12]:
import joblib
joblib.dump(model, "../../model/model.pkl")

['../../model/model.pkl']

In [8]:
df_reduced.to_csv(str(PROJECT_ROOT / "bench" / "correct_dataset.csv"))

In [ ]:
# correct_file = str(PROJECT_ROOT / "bench" / "correct_dataset.csv")
# incorrect_file = str(PROJECT_ROOT / "bench" / "incorrect_dataset.csv")

# # Чтение файлов
# try:
#     correct_df = pd.read_csv(correct_file)
#     incorrect_df = pd.read_csv(incorrect_file)
# except FileNotFoundError as e:
#     print(f"Ошибка: Файл не найден — {e}")
#     exit()
# except Exception as e:
#     print(f"Ошибка при чтении файлов: {e}")
#     exit()

# # Проверка, что датафреймы имеют одинаковую структуру (количество строк и столбцов)
# if correct_df.shape != incorrect_df.shape:
#     print("Предупреждение: Форматы датафреймов отличаются. Сравнение может быть некорректным.")

# # Список для хранения имён столбцов с несовпадениями
# columns_with_discrepancies = []

# # Перебор столбцов и сравнение значений
# for column in correct_df.columns:
#     # Проверяем, есть ли столбец в обоих датафреймах
#     if column not in incorrect_df.columns:
#         columns_with_discrepancies.append(column)
#         continue

#     # Сравниваем значения в столбце, игнорируя NaN (NaN != NaN)
#     comparison = correct_df[column].equals(incorrect_df[column])
#     if not comparison:
#         # Более детальная проверка: ищем конкретные несовпадения
#         mask = (correct_df[column] != incorrect_df[column]) & \
#                 (~correct_df[column].isna()) & \
#                 (~incorrect_df[column].isna())
#         if mask.any() or len(correct_df[column]) != len(incorrect_df[column]):
#             columns_with_discrepancies.append(column)

# # Вывод результата
# if columns_with_discrepancies:
#     print("Столбцы с несовпадениями:")
#     for col in columns_with_discrepancies:
#         print(f"- {col}")
# else:
#     print("Все столбцы совпадают.")

Столбцы с несовпадениями:
- contact_region_pvz
- lead_utm_device_type
- sale_hour
- sale_ts
- contact_to_lead_hours