In [1]:
from pathlib import Path
import pandas as pd
import sys
from catboost import CatBoostClassifier, Pool, EFstrType
from sklearn.metrics import roc_auc_score, log_loss, average_precision_score

# путь до корня проекта
PROJECT_ROOT = Path("../../").resolve()

# добавляем в PYTHONPATH
sys.path.append(str(PROJECT_ROOT))

from src.utils.preprocess import (
    preprocess_initial_dataset,
    split_dataset,
    remove_log_features,
    split_dataset_with_val,
    train_catboost_model,
    get_feature_importance_df
)


pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

DATA_PATH = Path("../../data/cleaned_dataset/final_dataset_from_notebooks.csv")
RAW_DATA_PATH = Path("../../data/raw/clean_dataset.csv")

In [2]:
df = pd.read_csv(DATA_PATH)
df_raw = pd.read_csv(RAW_DATA_PATH)
df = df.merge(
    df_raw[
        ["row_id", "lead_Стоимость доставки", "lead_Масса (гр)", "lead_Высота"]
    ],
    on="row_id",
    how="left",
)
df = remove_log_features(df)
del df_raw
# Приводим всё к нужному типу
df = preprocess_initial_dataset(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17966 entries, 0 to 18787
Columns: 110 entries, contact_pvz_code to contact_has_pvz_code
dtypes: datetime64[ns](2), float64(18), int64(64), object(26)
memory usage: 15.2+ MB

C:\Users\Михаил\AppData\Local\Temp\ipykernel_18728\3613829215.py:2: DtypeWarning: Columns (79,80,81) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv(RAW_DATA_PATH)

In [3]:
print(*df.columns.tolist(), sep="\n")

contact_pvz_code
lead_weight_gm
lead_responsible_user_id
lead_utm_group
lead_utm_referrer
lead_tags
lead_utm_source
lead_Квалификация лида
is_responsible_same
has_weight
contact_region_pvz
lead_utm_referrer_site
lead_has_roistat
lead_utm_id_1
lead_utm_id_2
lead_utm_id_3
lead_utm_device_type
lead_utm_site
lead_utm_position
lead_utm_reatrgeting_id
lead_utm_region_name
lead_is_utm_campaign_type_1
contact_Город
contact_region
lead_manager_category
lead_rate_is_warehouse_to_warehouse
lead_formname_has_value
lead_has_creation_date
lead_creation_date_week
lead_creation_date_month
lead_creation_date_quarter
lead_creation_date_dayofweek
lead_creation_date_sin
lead_creation_date_cos
sale_date_month
sale_date_quarter
sale_date_dayofweek
sale_date_week
sale_date_sin
sale_date_cos
lead_items_count
lead_total_quantity
lead_total_cost_from_composition
lead_has_health_supplement
lead_has_pillow
lead_has_mattress
lead_has_brace
lead_has_footwear
lead_has_accessory
lead_has_health_product
lead_categories_count
lead_has_linear_width
lead_linear_width
lead_discount_category
lead_discount
sale_hour
sale_dayofweek
sale_month
sale_ts
lead_source
timedelta_between_sale_and_creation
lead_created_ts
lead_created_dayofweek
lead_created_hour
lead_created_month
lead_has_shipping_cost
lead_shipping_cost
lead_has_length
lead_length
lead_price
lead_group_id
buyout_flag
width_cat
width_is_missing
lead_payment_type
lead_delivery_type
lead_group_id_missing
lead_group_quality
lead_mass_known
contact_to_lead_hours
contact_missing
contact_hour
contact_dayofweek
contact_month
contact_is_weekend
is_paid_traffic
lead_category_freq
is_feature_phone
lead_utm_campaign_missing
lead_utm_campaign_grouped
traffic_source_missing
traffic_source_grouped
utm_term_missing
utm_term_grouped
utm_sky_missing
utm_sky_autotarget
utm_sky_brand
utm_sky_varicose
utm_sky_sleep
lead_group_missing
lead_group_grouped
problem_missing
problem_grouped
lead_height_known
lead_height_bin
delivery_cost_missing
lead_Стоимость доставки
lead_Масса (гр)
lead_Высота
contact_has_pvz_code

In [4]:
def evaluate(model, X, y):
    y_refuse = (y == 0).astype(int)
    proba_refuse = model.predict_proba(X)[:, 0]
    return {
        "ROC_AUC": roc_auc_score(y_refuse, proba_refuse),
        "PR_AUC": average_precision_score(y_refuse, proba_refuse),
        "LogLoss": log_loss(y, model.predict_proba(X)),
    }

Обучаем датасет на всех признаках, чтобы посмотреть, какие признаки имеют наибольшее влияние на модель и есть ли среди них утечки

In [5]:
target = "buyout_flag"

X = df.drop(columns=[target, "sale_ts"])
y = df[target]

cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

train_pool = Pool(X, y, cat_features=cat_features)

model = CatBoostClassifier(
    iterations=300,
    depth=6,
    learning_rate=0.1,
    verbose=50,
    random_seed=42,
)

model.fit(train_pool)

0:	learn: 0.6411631	total: 217ms	remaining: 1m 4s
50:	learn: 0.4057866	total: 3.92s	remaining: 19.1s
100:	learn: 0.3931512	total: 7.71s	remaining: 15.2s
150:	learn: 0.3814602	total: 11.6s	remaining: 11.5s
200:	learn: 0.3703261	total: 15.6s	remaining: 7.67s
250:	learn: 0.3586711	total: 19.6s	remaining: 3.82s
299:	learn: 0.3510226	total: 23.5s	remaining: 0us

In [6]:
fi = pd.DataFrame(
    {
        "feature": X.columns,
        "importance": model.get_feature_importance(train_pool),
    },
).sort_values(by="importance", ascending=False)

fi.head(20)

                                feature  importance
72                    lead_payment_type    5.439240
66                      lead_has_length    4.756968
60                      lead_created_ts    4.094471
59  timedelta_between_sale_and_creation    3.492951
42     lead_total_cost_from_composition    2.681770
68                           lead_price    2.625012
5                             lead_tags    2.494132
76                      lead_mass_known    2.469882
16                 lead_utm_device_type    2.424856
75                   lead_group_quality    2.422282
7                lead_Квалификация лида    2.381270
1                        lead_weight_gm    2.109424
73                   lead_delivery_type    2.075912
67                          lead_length    1.911137
26              lead_formname_has_value    1.826223
70                            width_cat    1.717077
65                   lead_shipping_cost    1.675397
17                        lead_utm_site    1.584652
52                    lead_linear_width    1.582970
62                    lead_created_hour    1.571377

In [7]:
df = df.sort_values("sale_ts")

X_train, y_train, X_test, y_test = split_dataset(df)

cat_features = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

model = CatBoostClassifier(
    iterations=300,
    depth=6,
    learning_rate=0.1,
    verbose=0,
    cat_features=cat_features,
    random_state=42,
    )


model.fit(X_train, y_train)

metrics_full  = evaluate(model, X_test, y_test)
print("TIME SPLIT:", metrics_full)

TIME SPLIT: {'ROC_AUC': 0.6638482777589708, 'PR_AUC': 0.3887107605370326, 'LogLoss': 0.4305280496738976}

Удаляем из модели субъективную оценку менеджеров

In [8]:
df_reduced = df.drop(columns=["lead_Квалификация лида"])

X_train, y_train, X_test, y_test = split_dataset(df_reduced)

cat_features = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

model = CatBoostClassifier(
    iterations=300,
    depth=6,
    learning_rate=0.1,
    verbose=0,
    cat_features=cat_features,
    random_state=42,
    )


model.fit(X_train, y_train)

metrics_reduced  = evaluate(model, X_test, y_test)
print("TIME SPLIT:", metrics_reduced)

TIME SPLIT: {'ROC_AUC': 0.6595262779282329, 'PR_AUC': 0.36881750358120025, 'LogLoss': 0.4403641513824959}

In [10]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.head(20)

                                 feature  importance
67                            lead_price    3.486347
71                     lead_payment_type    3.128050
41      lead_total_cost_from_composition    3.083818
5                              lead_tags    3.033921
58   timedelta_between_sale_and_creation    2.967541
59                       lead_created_ts    2.864561
15                  lead_utm_device_type    2.724714
74                    lead_group_quality    2.588464
12                         lead_utm_id_1    2.246633
105                          lead_Высота    2.045763
76                 contact_to_lead_hours    2.014639
37                         sale_date_sin    2.009292
99                       problem_grouped    2.001539
40                   lead_total_quantity    1.988667
39                      lead_items_count    1.735417
36                        sale_date_week    1.677476
2               lead_responsible_user_id    1.643010
65                       lead_has_length    1.617156
72                    lead_delivery_type    1.600203
56                            sale_month    1.569043

Удаляем lead_group_quality так как потенциально содержит данные из будущего

In [11]:
df_reduced = df_reduced.drop(columns=["lead_group_quality"])

X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_reduced)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления lead_group_quality:", metrics)

0:	test: 0.4948507	best: 0.4948507 (0)	total: 60.9ms	remaining: 2m 1s
100:	test: 0.6347789	best: 0.6347789 (100)	total: 5.95s	remaining: 1m 51s
200:	test: 0.6358455	best: 0.6363337 (167)	total: 12.5s	remaining: 1m 51s
300:	test: 0.6377640	best: 0.6393592 (285)	total: 19s	remaining: 1m 47s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.639359198
bestIteration = 285

Shrink model to first 286 iterations.
Метрики после удаления lead_group_quality: {'ROC_AUC': 0.678800461238998, 'PR_AUC': 0.4062804622876623, 'LogLoss': 0.46344676536329676}

In [12]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.head(20)

                              feature  importance
71                  lead_payment_type   11.889413
59                    lead_created_ts    4.483890
104                       lead_Высота    4.109042
15               lead_utm_device_type    3.778163
99                  lead_height_known    3.052347
75              contact_to_lead_hours    2.867246
3                      lead_utm_group    2.770163
84          lead_utm_campaign_missing    2.553224
67                         lead_price    2.546965
6                     lead_utm_source    2.138551
41   lead_total_cost_from_composition    2.115333
68                      lead_group_id    2.059478
88                   utm_term_missing    2.055593
101             delivery_cost_missing    1.919140
5                           lead_tags    1.734972
100                   lead_height_bin    1.713941
18            lead_utm_reatrgeting_id    1.672606
57                        lead_source    1.667610
65                    lead_has_length    1.660098
12                      lead_utm_id_1    1.629822

In [13]:
columns_to_drop = fi[fi["importance"] < 0.2]["feature"].to_list()
df_removed_unimportant = df_reduced.drop(columns=columns_to_drop)

In [14]:
X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
    df_removed_unimportant
)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления хвоста fi:", metrics)

0:	test: 0.4919216	best: 0.4919216 (0)	total: 57.9ms	remaining: 1m 55s
100:	test: 0.6236221	best: 0.6267876 (84)	total: 5.65s	remaining: 1m 46s
200:	test: 0.6259418	best: 0.6275276 (152)	total: 11.7s	remaining: 1m 44s
300:	test: 0.6282397	best: 0.6307646 (282)	total: 18.1s	remaining: 1m 42s
400:	test: 0.6308983	best: 0.6312061 (372)	total: 24.8s	remaining: 1m 38s
500:	test: 0.6302982	best: 0.6316042 (431)	total: 31.3s	remaining: 1m 33s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6316041505
bestIteration = 431

Shrink model to first 432 iterations.
Метрики после удаления хвоста fi: {'ROC_AUC': 0.6475509901828029, 'PR_AUC': 0.3375712025538554, 'LogLoss': 0.4891234562649383}

In [15]:
# baseline_pr_auc = 0.4062804622876623

# results = []

# for feature in fi["feature"]:
#     print(f"\nУдаляем признак: {feature}")

#     df_removed = df_reduced.drop(columns=[feature])

#     X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
#         df_removed
#     )

#     model, metrics = train_catboost_model(
#         X_train, y_train, X_val, y_val, X_test, y_test
#     )

#     pr_auc = metrics["PR_AUC"]

#     print(f"PR_AUC: {pr_auc:.6f}")

#     results.append((feature, pr_auc))

#     # проверка улучшения
#     if pr_auc > baseline_pr_auc:
#         print(f"✅ Улучшение! Удаление признака {feature} дало PR_AUC = {pr_auc:.6f}")

In [16]:
results_df = pd.DataFrame(results, columns=["feature", "pr_auc"])
results_df = results_df.sort_values(by="pr_auc", ascending=False)

print(results_df[results_df["pr_auc"] > baseline_pr_auc])

NameError: name 'results' is not defined

Удаляем `sale_hour`

In [ ]:
df_reduced = df_reduced.drop(columns=["sale_hour"])
X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
    df_reduced
)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления признаков от sale_ts:", metrics)

0:	test: 0.5932611	best: 0.5932611 (0)	total: 70.9ms	remaining: 2m 21s
100:	test: 0.6309356	best: 0.6381838 (91)	total: 5.95s	remaining: 1m 51s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6381838139
bestIteration = 91

Shrink model to first 92 iterations.
Метрики после удаления признаков от sale_ts: {'ROC_AUC': 0.6887393153351389, 'PR_AUC': 0.41769757566691534, 'LogLoss': 0.49658491346134326}

In [ ]:
fi = get_feature_importance_df(model, X_train, y_train)

fi.tail(50)

                                 feature  importance
91                         utm_sky_brand    0.510259
84             lead_utm_campaign_grouped    0.499091
50                 lead_has_linear_width    0.480939
23                 lead_manager_category    0.417182
47                    lead_has_accessory    0.401992
32                lead_creation_date_cos    0.350947
60                     lead_created_hour    0.325130
29            lead_creation_date_quarter    0.293722
18               lead_utm_reatrgeting_id    0.286869
49                 lead_categories_count    0.246833
19                  lead_utm_region_name    0.245835
28              lead_creation_date_month    0.224777
40                   lead_total_quantity    0.220303
95                    lead_group_grouped    0.201907
79                    contact_is_weekend    0.196129
100                delivery_cost_missing    0.194367
104                 contact_has_pvz_code    0.185877
59                lead_created_dayofweek    0.185483
98                     lead_height_known    0.174981
30          lead_creation_date_dayofweek    0.173898
16                         lead_utm_site    0.168422
31                lead_creation_date_sin    0.167262
33                       sale_date_month    0.117269
34                     sale_date_quarter    0.093319
80                       is_paid_traffic    0.080299
89                       utm_sky_missing    0.079511
51                     lead_linear_width    0.053568
21                         contact_Город    0.049192
86                traffic_source_grouped    0.048172
0                       contact_pvz_code    0.012717
93                         utm_sky_sleep    0.009959
2               lead_responsible_user_id    0.006600
24   lead_rate_is_warehouse_to_warehouse    0.000000
8                             has_weight    0.000000
11                      lead_has_roistat    0.000000
9                     contact_region_pvz    0.000000
20           lead_is_utm_campaign_type_1    0.000000
12                         lead_utm_id_1    0.000000
42            lead_has_health_supplement    0.000000
44                     lead_has_mattress    0.000000
45                        lead_has_brace    0.000000
46                     lead_has_footwear    0.000000
72                 lead_group_id_missing    0.000000
43                       lead_has_pillow    0.000000
48               lead_has_health_product    0.000000
75                       contact_missing    0.000000
88                      utm_term_grouped    0.000000
82                      is_feature_phone    0.000000
96                       problem_missing    0.000000
92                      utm_sky_varicose    0.000000

In [77]:
baseline_pr_auc = 0.41769757566691534

for n in range(90, 29, -1):
    col_to_drop = fi["feature"].tail(n).to_list()

    df_test = df_reduced.drop(columns=col_to_drop)

    X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(df_test)

    model, metrics = train_catboost_model(
        X_train, y_train, X_val, y_val, X_test, y_test
    )

    pr_auc = metrics["PR_AUC"]

    print(f"tail({n}) -> PR_AUC: {pr_auc:.6f}")

    if pr_auc > baseline_pr_auc:
        print("\nIMPROVEMENT FOUND")
        print(f"tail({n}) gives PR_AUC = {pr_auc:.6f} (baseline = {baseline_pr_auc})")
        break

0:	test: 0.5782315	best: 0.5782315 (0)	total: 43.2ms	remaining: 1m 26s
100:	test: 0.6193590	best: 0.6205655 (94)	total: 3.89s	remaining: 1m 13s
200:	test: 0.6247509	best: 0.6247540 (198)	total: 7.71s	remaining: 1m 9s
300:	test: 0.6303013	best: 0.6305127 (274)	total: 11.8s	remaining: 1m 6s
400:	test: 0.6292860	best: 0.6333361 (332)	total: 15.8s	remaining: 1m 3s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6333361319
bestIteration = 332

Shrink model to first 333 iterations.
tail(90) -> PR_AUC: 0.366716
0:	test: 0.5737725	best: 0.5737725 (0)	total: 40.5ms	remaining: 1m 20s
100:	test: 0.6287870	best: 0.6325354 (65)	total: 3.82s	remaining: 1m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6325354403
bestIteration = 65

Shrink model to first 66 iterations.
tail(89) -> PR_AUC: 0.386414
0:	test: 0.5949185	best: 0.5949185 (0)	total: 39.1ms	remaining: 1m 18s
100:	test: 0.6437793	best: 0.6441758 (88)	total: 3.96s	remaining: 1m 14s
200:	test: 0.6445256	best: 0.6453760 (106)	total: 7.83s	remaining: 1m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6453760452
bestIteration = 106

Shrink model to first 107 iterations.
tail(88) -> PR_AUC: 0.402849
0:	test: 0.5632469	best: 0.5632469 (0)	total: 42ms	remaining: 1m 23s
100:	test: 0.6426459	best: 0.6443359 (97)	total: 3.84s	remaining: 1m 12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6443359235
bestIteration = 97

Shrink model to first 98 iterations.
tail(87) -> PR_AUC: 0.392437
0:	test: 0.5961856	best: 0.5961856 (0)	total: 39.9ms	remaining: 1m 19s
100:	test: 0.6349391	best: 0.6434435 (36)	total: 4.02s	remaining: 1m 15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6434435023
bestIteration = 36

Shrink model to first 37 iterations.
tail(86) -> PR_AUC: 0.388818
0:	test: 0.5202303	best: 0.5202303 (0)	total: 40.7ms	remaining: 1m 21s
100:	test: 0.6388959	best: 0.6388959 (100)	total: 4.08s	remaining: 1m 16s
200:	test: 0.6372074	best: 0.6388959 (100)	total: 7.83s	remaining: 1m 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6388958852
bestIteration = 100

Shrink model to first 101 iterations.
tail(85) -> PR_AUC: 0.391499
0:	test: 0.5860425	best: 0.5860425 (0)	total: 41.2ms	remaining: 1m 22s
100:	test: 0.6466774	best: 0.6466774 (100)	total: 4.23s	remaining: 1m 19s
200:	test: 0.6406512	best: 0.6466774 (100)	total: 8.04s	remaining: 1m 11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6466773633
bestIteration = 100

Shrink model to first 101 iterations.
tail(84) -> PR_AUC: 0.364819
0:	test: 0.6033187	best: 0.6033187 (0)	total: 42ms	remaining: 1m 24s
100:	test: 0.6484669	best: 0.6484669 (100)	total: 4.3s	remaining: 1m 20s
200:	test: 0.6434513	best: 0.6511457 (130)	total: 8.13s	remaining: 1m 12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6511456885
bestIteration = 130

Shrink model to first 131 iterations.
tail(83) -> PR_AUC: 0.385962
0:	test: 0.5646368	best: 0.5646368 (0)	total: 42.1ms	remaining: 1m 24s
100:	test: 0.6404662	best: 0.6412124 (84)	total: 3.98s	remaining: 1m 14s
200:	test: 0.6469059	best: 0.6469681 (199)	total: 7.95s	remaining: 1m 11s
300:	test: 0.6549657	best: 0.6552642 (270)	total: 12.3s	remaining: 1m 9s
400:	test: 0.6497604	best: 0.6555534 (311)	total: 16.7s	remaining: 1m 6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6555533789
bestIteration = 311

Shrink model to first 312 iterations.
tail(82) -> PR_AUC: 0.387552
0:	test: 0.5966287	best: 0.5966287 (0)	total: 42.3ms	remaining: 1m 24s
100:	test: 0.6374173	best: 0.6380206 (59)	total: 4.09s	remaining: 1m 16s
200:	test: 0.6406559	best: 0.6407274 (197)	total: 8.28s	remaining: 1m 14s
300:	test: 0.6413026	best: 0.6431901 (258)	total: 12.8s	remaining: 1m 12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6431900795
bestIteration = 258

Shrink model to first 259 iterations.
tail(81) -> PR_AUC: 0.365948
0:	test: 0.5828428	best: 0.5828428 (0)	total: 42.6ms	remaining: 1m 25s
100:	test: 0.6368436	best: 0.6404024 (78)	total: 4.4s	remaining: 1m 22s
200:	test: 0.6418312	best: 0.6422230 (125)	total: 8.53s	remaining: 1m 16s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6422230307
bestIteration = 125

Shrink model to first 126 iterations.
tail(80) -> PR_AUC: 0.385968
0:	test: 0.4998352	best: 0.4998352 (0)	total: 43ms	remaining: 1m 25s
100:	test: 0.6393017	best: 0.6404024 (95)	total: 4.54s	remaining: 1m 25s
200:	test: 0.6359372	best: 0.6417488 (127)	total: 8.66s	remaining: 1m 17s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6417488347
bestIteration = 127

Shrink model to first 128 iterations.
tail(79) -> PR_AUC: 0.372195
0:	test: 0.6051533	best: 0.6051533 (0)	total: 41.8ms	remaining: 1m 23s
100:	test: 0.6379817	best: 0.6390420 (94)	total: 4.38s	remaining: 1m 22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6390420309
bestIteration = 94

Shrink model to first 95 iterations.
tail(78) -> PR_AUC: 0.362582
0:	test: 0.5937789	best: 0.5937789 (0)	total: 45.4ms	remaining: 1m 30s
100:	test: 0.6404320	best: 0.6412700 (85)	total: 4.29s	remaining: 1m 20s
200:	test: 0.6413928	best: 0.6465328 (162)	total: 8.48s	remaining: 1m 15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6465327724
bestIteration = 162

Shrink model to first 163 iterations.
tail(77) -> PR_AUC: 0.362486
0:	test: 0.4833518	best: 0.4833518 (0)	total: 41.9ms	remaining: 1m 23s
100:	test: 0.6420955	best: 0.6480844 (92)	total: 4.33s	remaining: 1m 21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6480844038
bestIteration = 92

Shrink model to first 93 iterations.
tail(76) -> PR_AUC: 0.405888
0:	test: 0.5281424	best: 0.5281424 (0)	total: 41.3ms	remaining: 1m 22s
100:	test: 0.6574004	best: 0.6574175 (96)	total: 4.28s	remaining: 1m 20s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6574175132
bestIteration = 96

Shrink model to first 97 iterations.
tail(75) -> PR_AUC: 0.384604
0:	test: 0.5153577	best: 0.5153577 (0)	total: 42.8ms	remaining: 1m 25s
100:	test: 0.6401490	best: 0.6401490 (100)	total: 4.37s	remaining: 1m 22s
200:	test: 0.6382429	best: 0.6415358 (103)	total: 8.68s	remaining: 1m 17s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6415358352
bestIteration = 103

Shrink model to first 104 iterations.
tail(74) -> PR_AUC: 0.379631
0:	test: 0.6144802	best: 0.6144802 (0)	total: 48.8ms	remaining: 1m 37s
100:	test: 0.6397199	best: 0.6441120 (73)	total: 4.56s	remaining: 1m 25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6441120408
bestIteration = 73

Shrink model to first 74 iterations.
tail(73) -> PR_AUC: 0.380482
0:	test: 0.4650992	best: 0.4650992 (0)	total: 43.7ms	remaining: 1m 27s
100:	test: 0.6312932	best: 0.6360663 (74)	total: 4.53s	remaining: 1m 25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6360662568
bestIteration = 74

Shrink model to first 75 iterations.
tail(72) -> PR_AUC: 0.356845
0:	test: 0.5280911	best: 0.5280911 (0)	total: 43.9ms	remaining: 1m 27s
100:	test: 0.6510446	best: 0.6521205 (70)	total: 4.42s	remaining: 1m 23s
200:	test: 0.6517878	best: 0.6534545 (177)	total: 8.88s	remaining: 1m 19s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6534544787
bestIteration = 177

Shrink model to first 178 iterations.
tail(71) -> PR_AUC: 0.340124
0:	test: 0.5848873	best: 0.5848873 (0)	total: 42.6ms	remaining: 1m 25s
100:	test: 0.6481248	best: 0.6493126 (95)	total: 4.51s	remaining: 1m 24s
200:	test: 0.6466572	best: 0.6509265 (121)	total: 8.87s	remaining: 1m 19s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6509264701
bestIteration = 121

Shrink model to first 122 iterations.
tail(70) -> PR_AUC: 0.391313
0:	test: 0.5919676	best: 0.5919676 (0)	total: 45.3ms	remaining: 1m 30s
100:	test: 0.6338088	best: 0.6357864 (84)	total: 4.63s	remaining: 1m 27s
200:	test: 0.6359636	best: 0.6385663 (132)	total: 9.08s	remaining: 1m 21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6385662802
bestIteration = 132

Shrink model to first 133 iterations.
tail(69) -> PR_AUC: 0.323904
0:	test: 0.5749432	best: 0.5749432 (0)	total: 45ms	remaining: 1m 30s
100:	test: 0.6504414	best: 0.6508923 (96)	total: 4.45s	remaining: 1m 23s
200:	test: 0.6521361	best: 0.6544868 (153)	total: 8.75s	remaining: 1m 18s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6544868267
bestIteration = 153

Shrink model to first 154 iterations.
tail(68) -> PR_AUC: 0.357575
0:	test: 0.5638625	best: 0.5638625 (0)	total: 43.9ms	remaining: 1m 27s
100:	test: 0.6380579	best: 0.6390529 (80)	total: 4.65s	remaining: 1m 27s
200:	test: 0.6432212	best: 0.6446515 (195)	total: 9.23s	remaining: 1m 22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6446515359
bestIteration = 195

Shrink model to first 196 iterations.
tail(67) -> PR_AUC: 0.336161
0:	test: 0.5234657	best: 0.5234657 (0)	total: 42.8ms	remaining: 1m 25s
100:	test: 0.6436036	best: 0.6447930 (63)	total: 4.58s	remaining: 1m 26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6447930173
bestIteration = 63

Shrink model to first 64 iterations.
tail(66) -> PR_AUC: 0.387395
0:	test: 0.4999813	best: 0.4999813 (0)	total: 43.4ms	remaining: 1m 26s
100:	test: 0.6311066	best: 0.6311066 (100)	total: 4.41s	remaining: 1m 22s
200:	test: 0.6353853	best: 0.6353853 (200)	total: 8.81s	remaining: 1m 18s
300:	test: 0.6340606	best: 0.6362995 (204)	total: 13.6s	remaining: 1m 16s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.636299468
bestIteration = 204

Shrink model to first 205 iterations.
tail(65) -> PR_AUC: 0.362533
0:	test: 0.5075871	best: 0.5075871 (0)	total: 19.7ms	remaining: 39.4s
100:	test: 0.6345830	best: 0.6365202 (81)	total: 4.54s	remaining: 1m 25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6365202412
bestIteration = 81

Shrink model to first 82 iterations.
tail(64) -> PR_AUC: 0.412127
0:	test: 0.5581147	best: 0.5581147 (0)	total: 44.8ms	remaining: 1m 29s
100:	test: 0.6371888	best: 0.6391291 (75)	total: 4.61s	remaining: 1m 26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6391290964
bestIteration = 75

Shrink model to first 76 iterations.
tail(63) -> PR_AUC: 0.410331
0:	test: 0.5077799	best: 0.5077799 (0)	total: 54.7ms	remaining: 1m 49s
100:	test: 0.6348504	best: 0.6349002 (96)	total: 4.7s	remaining: 1m 28s
200:	test: 0.6329599	best: 0.6354817 (101)	total: 9.31s	remaining: 1m 23s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6354816743
bestIteration = 101

Shrink model to first 102 iterations.
tail(62) -> PR_AUC: 0.377430
0:	test: 0.5457140	best: 0.5457140 (0)	total: 47.4ms	remaining: 1m 34s
100:	test: 0.6443406	best: 0.6453729 (84)	total: 4.86s	remaining: 1m 31s
200:	test: 0.6445645	best: 0.6482803 (130)	total: 9.55s	remaining: 1m 25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6482803011
bestIteration = 130

Shrink model to first 131 iterations.
tail(61) -> PR_AUC: 0.416282
0:	test: 0.5067522	best: 0.5067522 (0)	total: 49ms	remaining: 1m 37s
100:	test: 0.6297789	best: 0.6299095 (96)	total: 4.84s	remaining: 1m 30s
200:	test: 0.6320675	best: 0.6336098 (144)	total: 9.79s	remaining: 1m 27s
300:	test: 0.6376770	best: 0.6376770 (300)	total: 15.1s	remaining: 1m 25s
400:	test: 0.6372074	best: 0.6376770 (300)	total: 20.4s	remaining: 1m 21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6376769684
bestIteration = 300

Shrink model to first 301 iterations.
tail(60) -> PR_AUC: 0.369788
0:	test: 0.5382699	best: 0.5382699 (0)	total: 50ms	remaining: 1m 39s
100:	test: 0.6443484	best: 0.6443608 (99)	total: 4.93s	remaining: 1m 32s
200:	test: 0.6436130	best: 0.6456839 (123)	total: 9.67s	remaining: 1m 26s
300:	test: 0.6465359	best: 0.6470241 (293)	total: 14.8s	remaining: 1m 23s
400:	test: 0.6480347	best: 0.6491510 (347)	total: 20.1s	remaining: 1m 20s
500:	test: 0.6475278	best: 0.6497729 (432)	total: 25.3s	remaining: 1m 15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6497728524
bestIteration = 432

Shrink model to first 433 iterations.
tail(59) -> PR_AUC: 0.359736
0:	test: 0.5836575	best: 0.5836575 (0)	total: 48.1ms	remaining: 1m 36s
100:	test: 0.6437529	best: 0.6458673 (71)	total: 4.87s	remaining: 1m 31s
200:	test: 0.6334294	best: 0.6464115 (112)	total: 9.9s	remaining: 1m 28s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6464115026
bestIteration = 112

Shrink model to first 113 iterations.
tail(58) -> PR_AUC: 0.403284
0:	test: 0.5481597	best: 0.5481597 (0)	total: 50.8ms	remaining: 1m 41s
100:	test: 0.6409699	best: 0.6410570 (93)	total: 5.27s	remaining: 1m 39s
200:	test: 0.6453045	best: 0.6454196 (195)	total: 10.2s	remaining: 1m 30s
300:	test: 0.6469339	best: 0.6479009 (270)	total: 15.8s	remaining: 1m 29s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6479009443
bestIteration = 270

Shrink model to first 271 iterations.
tail(57) -> PR_AUC: 0.368069
0:	test: 0.4879710	best: 0.4879710 (0)	total: 45ms	remaining: 1m 29s
100:	test: 0.6432616	best: 0.6432616 (100)	total: 5.17s	remaining: 1m 37s
200:	test: 0.6399345	best: 0.6455813 (114)	total: 10.3s	remaining: 1m 31s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.645581271
bestIteration = 114

Shrink model to first 115 iterations.
tail(56) -> PR_AUC: 0.408808
0:	test: 0.5577182	best: 0.5577182 (0)	total: 55.9ms	remaining: 1m 51s
100:	test: 0.6457803	best: 0.6462265 (53)	total: 5.39s	remaining: 1m 41s
200:	test: 0.6428107	best: 0.6469868 (110)	total: 11s	remaining: 1m 38s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6469867567
bestIteration = 110

Shrink model to first 111 iterations.
tail(55) -> PR_AUC: 0.389162
0:	test: 0.5368676	best: 0.5368676 (0)	total: 54.2ms	remaining: 1m 48s
100:	test: 0.6441758	best: 0.6441758 (100)	total: 5.38s	remaining: 1m 41s
200:	test: 0.6420862	best: 0.6451491 (166)	total: 10.5s	remaining: 1m 33s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.645149053
bestIteration = 166

Shrink model to first 167 iterations.
tail(54) -> PR_AUC: 0.394123
0:	test: 0.5319950	best: 0.5319950 (0)	total: 53.3ms	remaining: 1m 46s
100:	test: 0.6280469	best: 0.6299033 (94)	total: 5.37s	remaining: 1m 40s
200:	test: 0.6310165	best: 0.6313087 (191)	total: 10.6s	remaining: 1m 34s
300:	test: 0.6345986	best: 0.6351521 (251)	total: 16.3s	remaining: 1m 31s
400:	test: 0.6347727	best: 0.6354786 (341)	total: 21.9s	remaining: 1m 27s
500:	test: 0.6369525	best: 0.6373380 (479)	total: 27.7s	remaining: 1m 22s
600:	test: 0.6366571	best: 0.6373816 (533)	total: 33.3s	remaining: 1m 17s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6373815676
bestIteration = 533

Shrink model to first 534 iterations.
tail(53) -> PR_AUC: 0.351774
0:	test: 0.5779827	best: 0.5779827 (0)	total: 28.7ms	remaining: 57.4s
100:	test: 0.6486161	best: 0.6555192 (81)	total: 5.43s	remaining: 1m 42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6555191746
bestIteration = 81

Shrink model to first 82 iterations.
tail(52) -> PR_AUC: 0.362871
0:	test: 0.5923112	best: 0.5923112 (0)	total: 56.6ms	remaining: 1m 53s
100:	test: 0.6417939	best: 0.6439301 (73)	total: 5.2s	remaining: 1m 37s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6439301362
bestIteration = 73

Shrink model to first 74 iterations.
tail(51) -> PR_AUC: 0.375272
0:	test: 0.5615911	best: 0.5615911 (0)	total: 55.7ms	remaining: 1m 51s
100:	test: 0.6427796	best: 0.6438337 (90)	total: 5.46s	remaining: 1m 42s
200:	test: 0.6420427	best: 0.6452361 (127)	total: 10.9s	remaining: 1m 37s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6452361185
bestIteration = 127

Shrink model to first 128 iterations.
tail(50) -> PR_AUC: 0.385658
0:	test: 0.4998414	best: 0.4998414 (0)	total: 72.5ms	remaining: 2m 24s
100:	test: 0.6339300	best: 0.6352049 (86)	total: 5.96s	remaining: 1m 51s
200:	test: 0.6350215	best: 0.6364643 (186)	total: 11.2s	remaining: 1m 40s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6364642705
bestIteration = 186

Shrink model to first 187 iterations.
tail(49) -> PR_AUC: 0.383804
0:	test: 0.5238808	best: 0.5238808 (0)	total: 59ms	remaining: 1m 57s
100:	test: 0.6464550	best: 0.6475558 (92)	total: 5.74s	remaining: 1m 47s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6475557919
bestIteration = 92

Shrink model to first 93 iterations.
tail(48) -> PR_AUC: 0.404559
0:	test: 0.5213684	best: 0.5213684 (0)	total: 54.8ms	remaining: 1m 49s
100:	test: 0.6444836	best: 0.6489519 (62)	total: 5.42s	remaining: 1m 41s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6489519492
bestIteration = 62

Shrink model to first 63 iterations.
tail(47) -> PR_AUC: 0.392601
0:	test: 0.5787787	best: 0.5787787 (0)	total: 55.7ms	remaining: 1m 51s
100:	test: 0.6347416	best: 0.6347852 (97)	total: 5.65s	remaining: 1m 46s
200:	test: 0.6338212	best: 0.6375433 (123)	total: 11.3s	remaining: 1m 40s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6375432607
bestIteration = 123

Shrink model to first 124 iterations.
tail(46) -> PR_AUC: 0.366971
0:	test: 0.4998663	best: 0.4998663 (0)	total: 54.3ms	remaining: 1m 48s
100:	test: 0.6421422	best: 0.6448101 (58)	total: 5.51s	remaining: 1m 43s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6448101195
bestIteration = 58

Shrink model to first 59 iterations.
tail(45) -> PR_AUC: 0.361893
0:	test: 0.5916333	best: 0.5916333 (0)	total: 56.9ms	remaining: 1m 53s
100:	test: 0.6502579	best: 0.6519557 (76)	total: 5.45s	remaining: 1m 42s
200:	test: 0.6441447	best: 0.6557306 (135)	total: 11s	remaining: 1m 38s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6557306194
bestIteration = 135

Shrink model to first 136 iterations.
tail(44) -> PR_AUC: 0.407210
0:	test: 0.5487769	best: 0.5487769 (0)	total: 57.1ms	remaining: 1m 54s
100:	test: 0.6456093	best: 0.6485260 (83)	total: 5.74s	remaining: 1m 48s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6485259502
bestIteration = 83

Shrink model to first 84 iterations.
tail(43) -> PR_AUC: 0.373589
0:	test: 0.5488344	best: 0.5488344 (0)	total: 55.3ms	remaining: 1m 50s
100:	test: 0.6412591	best: 0.6414301 (96)	total: 5.58s	remaining: 1m 44s
200:	test: 0.6405688	best: 0.6426957 (106)	total: 11.3s	remaining: 1m 41s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6426956719
bestIteration = 106

Shrink model to first 107 iterations.
tail(42) -> PR_AUC: 0.337232
0:	test: 0.6145300	best: 0.6145300 (0)	total: 55.5ms	remaining: 1m 50s
100:	test: 0.6267751	best: 0.6267751 (100)	total: 5.58s	remaining: 1m 44s
200:	test: 0.6272882	best: 0.6280593 (116)	total: 11.1s	remaining: 1m 39s
300:	test: 0.6286533	best: 0.6294493 (212)	total: 17.2s	remaining: 1m 36s
400:	test: 0.6278510	best: 0.6310693 (365)	total: 23.4s	remaining: 1m 33s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6310693197
bestIteration = 365

Shrink model to first 366 iterations.
tail(41) -> PR_AUC: 0.337128
0:	test: 0.5190642	best: 0.5190642 (0)	total: 66.1ms	remaining: 2m 12s
100:	test: 0.6304225	best: 0.6374158 (57)	total: 5.76s	remaining: 1m 48s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6374157719
bestIteration = 57

Shrink model to first 58 iterations.
tail(40) -> PR_AUC: 0.373535
0:	test: 0.5844893	best: 0.5844893 (0)	total: 56.9ms	remaining: 1m 53s
100:	test: 0.6379506	best: 0.6407336 (64)	total: 5.83s	remaining: 1m 49s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6407335889
bestIteration = 64

Shrink model to first 65 iterations.
tail(39) -> PR_AUC: 0.358949

In [78]:
col_to_drop = fi["feature"].tail(61).to_list()

df_reduced = df_reduced.drop(columns=col_to_drop)
X_train, y_train, X_val, y_val, X_test, y_test = split_dataset_with_val(
    df_reduced
)

model, metrics = train_catboost_model(
    X_train, y_train, X_val, y_val, X_test, y_test
)

print("Метрики после удаления признаков от sale_ts:", metrics)

0:	test: 0.5457140	best: 0.5457140 (0)	total: 55.1ms	remaining: 1m 50s
100:	test: 0.6443406	best: 0.6453729 (84)	total: 5.31s	remaining: 1m 39s
200:	test: 0.6445645	best: 0.6482803 (130)	total: 10.3s	remaining: 1m 32s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6482803011
bestIteration = 130

Shrink model to first 131 iterations.
Метрики после удаления признаков от sale_ts: {'ROC_AUC': 0.6851922181787407, 'PR_AUC': 0.41628202143501164, 'LogLoss': 0.46627536716179624}

In [79]:
X_train.columns.to_list()

['lead_weight_gm',
 'lead_utm_group',
 'lead_tags',
 'lead_utm_source',
 'lead_utm_referrer_site',
 'lead_utm_id_2',
 'lead_utm_id_3',
 'lead_utm_device_type',
 'lead_utm_position',
 'lead_formname_has_value',
 'lead_has_creation_date',
 'sale_date_week',
 'sale_date_sin',
 'sale_date_cos',
 'lead_items_count',
 'lead_total_cost_from_composition',
 'lead_discount_category',
 'lead_discount',
 'sale_dayofweek',
 'sale_month',
 'lead_created_ts',
 'lead_created_month',
 'lead_has_shipping_cost',
 'lead_shipping_cost',
 'lead_has_length',
 'lead_length',
 'lead_price',
 'lead_group_id',
 'width_cat',
 'width_is_missing',
 'lead_payment_type',
 'lead_delivery_type',
 'lead_mass_known',
 'contact_to_lead_hours',
 'contact_hour',
 'lead_category_freq',
 'lead_utm_campaign_missing',
 'utm_term_missing',
 'utm_sky_autotarget',
 'lead_group_missing',
 'problem_grouped',
 'lead_height_bin',
 'lead_Масса (гр)',
 'lead_Высота']